name: ACME automation

on:
  push:
    branches: [ main ]
env:
  TZ: Asia/Shanghai
  acme.sh: /home/runner/.acme.sh/acme.sh
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: Install acme.sh
      run: curl https://get.acme.sh | sh
        
    - name: Check acme.sh
      run: ${acme.sh} -h
