name: ACME automation

on:
  workflow_dispatch:
    inputs:
      acme_server:
        description: 'ACME server'     
        required: true
        default: 'letsencrypt'
      dns:
        description: 'DNS provider'     
        required: true
        default: 'dns_dp'
      domain_name:
        description: 'Domain Name'     
        required: true
        default: 'wss.gcp.fly97.cn'
      
env:
  TZ: Asia/Shanghai
  acme: /home/runner/.acme.sh/acme.sh
  DP_Id: ${{ secrets.DP_Id }}
  DP_Key: ${{ secrets.DP_Key }}
jobs:
  build:
    name: Issue Certificate
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: Install acme.sh
      run: curl https://get.acme.sh | sh
        
    - name: Check acme.sh
      run: ${acme} -h
      
    - name: Register Zerossl account
      if: github.event.inputs.acme_server == 'zerossl'
      env:
        acme_server: ${{ github.event.inputs.acme_server }}
        eab_kid: ${{ secrets.eab_kid }}
        eab_hmac_key: ${{ secrets.eab_hmac_key }}
      run: |
        echo $acme_server
        $acme --register-account --server $acme_server --eab-kid $eab_kid --eab-hmac-key $eab_hmac_key
        
    - name: Register buypass account
      if: github.event.inputs.acme_server == 'buypass'
      env:
        acme_server: ${{ github.event.inputs.acme_server }}
        dns:  ${{ github.event.inputs.acme_server }}
        domain_name: ${{ github.event.inputs.domain_name }}
      run: |
        $acme --register-account --server $acme_server --accountemail wf.09@outlook.de
        
    - name: Issue certificate
      env:
        acme_server: ${{ github.event.inputs.acme_server }}
        dns:  ${{ github.event.inputs.acme_server }}
        domain_name: ${{ github.event.inputs.domain_name }}
      run: |
        $acme --server $acme_server --issue --dns $dns -d $domain_name
        
    - name: Deliver certificate
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.domain_name }}
        path: /home/runner/.acme.sh/${{ github.event.inputs.domain_name }}
        
      