name: ACME automation

on:
  push:
    branches: [ main ]
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: Install acme.sh
      run: |
        curl  https://get.acme.sh | bash
        alias acme.sh=~/.acme.sh/acme.sh
        acme.sh -h